---
# file: tasks/ubuntu.yaml

- name: Install Dependencies.
  apt:
    name: "{{ packages | flatten(levels=1) }}"
    state: "present"
    cache_valid_time: 3600
    install_recommends: false
  tags:
    - openrazer-inst-dependencies

- name: Add Openrazer Repository.
  apt_repository:
    repo: "{{ openrazer_apt_url }}"
    state: "{{ openrazer_apt_state }}"
    update_cache: true
  tags:
    - openrazer-conf-apt
