---
# file: tasks/ubuntu.yaml

- name: Ensure dependencies are installed.
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "python3-apt"
    state: "present"
    cache_valid_time: 3600
    install_recommends: False
  tags:
    - openrazer-inst-dependencies

- name: Add Openrazer repository.
  apt_repository:
    repo: "{{ openrazer_apt_url }}"
    state: "{{ openrazer_apt_state }}"
    update_cache: true
  tags:
    - openrazer-conf-apt
